version: 2

sources:
  - name: northwind
    database: northwind  
    schema: raw_northwind  
    tables:
      - name: customer
      - name: _order_
      - name: orderdetail
      - name: product